# Generated by Django 4.0.10 on 2023-10-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_stackelementtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stackelementtype',
            options={'verbose_name_plural': 'Stack Element Types'},
        ),
    ]
